-module(ar_translate).
-export([translate/1]).

% This module translate tree generated by arlang into erlang source code.

% [{{operator,1,'+'},{number,1,2},{number,1,2}}]

translate([{apply, {{Type, Line, Operation}, L, R}} | Rest]) when Type == operator -> 
  [{op, Line, Operation, L, R}] ++ Rest.
  

